services:
  - type: web
    name: web-chat-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn web_chat_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
