services:
  - type: web
    name: web-chat-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn web_chat_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
